 # Regularization
## Regularization attempts to minimize the RSS (residual sum of squares) and a penalty factor

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import scienceplots

In [2]:
df = pd.read_csv(r'C:\Users\Data\Advertising.csv\Advertising.csv', index_col=0)

In [3]:
df.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('Sales', axis=1)
y = df['Sales']

## Preprocessing  PolynomialFeatures

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_convert = PolynomialFeatures(degree=3, include_bias= False)

In [7]:
polynomial_features = polynomial_convert.fit_transform(X)

## Split data

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(polynomial_features, y, test_size=0.3, random_state=101)

## Scaling data

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
X_train = scaler.fit_transform(X_train)

In [13]:
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [15]:
X_test

array([[-0.91339472,  1.76259419,  0.68168558, ...,  2.09516506,
         0.89465642,  0.09868885],
       [ 1.23121149,  0.23655959, -1.19601922, ..., -0.62566104,
        -0.60402516, -0.54547726],
       [-0.46002473, -0.40776614,  0.35005115, ..., -0.43068575,
        -0.23635113, -0.15776394],
       ...,
       [-1.33115973,  1.19965698, -1.18200649, ..., -0.47847952,
        -0.59569585, -0.54528297],
       [ 1.3522684 , -0.23142436, -1.4389064 , ..., -0.7233135 ,
        -0.61591305, -0.54660193],
       [ 0.27818504, -0.06186496,  0.01841672, ..., -0.32290124,
        -0.28905624, -0.33528306]])

# Ridge Regression (L2)

In [16]:
from sklearn.linear_model import Ridge

In [17]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, normalize='deprecated', copy_X=True, max_iter=None, tol=0.001, solver='auto', positive=False, random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Regularization strength; must be 

In [18]:
ridge_model = Ridge(alpha=10)

In [19]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [20]:
predict_ridge = ridge_model.predict(X_test)

## Uji metrics ridge

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [22]:
MAE = mean_absolute_error(y_test, predict_ridge)
MSE = mean_squared_error(y_test, predict_ridge)
RMSE = np.sqrt(MSE)

In [23]:
MAE

0.5774404204714166

In [24]:
RMSE

0.8946386461319675

In [25]:
# perbandigan dengan train prediction
train_predict = ridge_model.predict(X_train)
MAE = mean_absolute_error(y_train, train_predict)
MAE

0.5288348183025329

## Choosing alpha value with Cross Validation | K-fold

In [26]:
from sklearn.linear_model import RidgeCV

In [27]:
help(RidgeCV)

Help on class RidgeCV in module sklearn.linear_model._ridge:

class RidgeCV(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidgeCV)
 |  RidgeCV(alphas=(0.1, 1.0, 10.0), *, fit_intercept=True, normalize='deprecated', scoring=None, cv=None, gcv_mode=None, store_cv_values=False, alpha_per_target=False)
 |  
 |  Ridge regression with built-in cross-validation.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  By default, it performs efficient Leave-One-Out Cross-Validation.
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alphas : ndarray of shape (n_alphas,), default=(0.1, 1.0, 10.0)
 |      Array of alpha values to try.
 |      Regularization strength; must be a positive float. Regularization
 |      improves the conditioning of the problem and reduces the variance of
 |      the estimates. Larger values specify stronger regularization.
 |      Alpha corresponds to ``1 / (2C)`` in other lin

In [28]:
RidgeCV_model = RidgeCV(alphas=(0.1, 1.0, 10), scoring='neg_mean_squared_error')

In [29]:
RidgeCV_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_squared_error')

In [30]:
RidgeCV_model.alpha_

0.1

In [31]:
test_prediction = RidgeCV_model.predict(X_test)

## Uji metrics RidgeCV

In [32]:
MAE = mean_absolute_error(y_test,test_prediction )
MSE = mean_squared_error(y_test, test_prediction)
RMSE = np.sqrt(MSE)

In [33]:
MAE

0.42737748843249934

In [34]:
MSE

0.38201298815070234

In [35]:
RMSE

0.6180719926923581

In [36]:
# Training set performent
train_ridgecv = RidgeCV_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_ridgecv)
MAE

0.3094132105641705

In [37]:
RidgeCV_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

---
----
# Lasso L2

In [38]:
from sklearn.linear_model import Lasso, LassoCV

In [39]:
help(LassoCV)

Help on class LassoCV in module sklearn.linear_model._coordinate_descent:

class LassoCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  LassoCV(*, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, normalize='deprecated', precompute='auto', max_iter=1000, tol=0.0001, copy_X=True, cv=None, verbose=False, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Lasso linear model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  The best model is selected by cross-validation.
 |  
 |  The optimization objective for Lasso is::
 |  
 |      (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
 |  
 |  Read more in the :ref:`User Guide <lasso>`.
 |  
 |  Parameters
 |  ----------
 |  eps : float, default=1e-3
 |      Length of the path. ``eps=1e-3`` means that
 |      ``alpha_min / alpha_max = 1e-3``.
 |  
 |  n_alphas : int, default=100
 |      Number of alphas along the regulariz

In [40]:
lassoCV_model = LassoCV(eps = 0.1, n_alphas =100, cv=5)

In [41]:
lassoCV_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [42]:
lassoCV_model.alpha_

0.49430709092258285

In [43]:
test_prediction = lassoCV_model.predict(X_test)

In [44]:
MAE = mean_absolute_error(y_test, test_prediction)
MSE = mean_squared_error(y_test, test_prediction)
RMSE = np.sqrt(MSE)

In [45]:
MAE

0.6541723161252858

In [46]:
RMSE

1.1308001022762542

In [47]:
lassoCV_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

---
---
# ElasticNET
## Gabungan L1 dan L2 atau (Rigde dan Lasso)

In [48]:
from sklearn.linear_model import ElasticNetCV

In [49]:
help(ElasticNetCV)

Help on class ElasticNetCV in module sklearn.linear_model._coordinate_descent:

class ElasticNetCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  ElasticNetCV(*, l1_ratio=0.5, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, normalize='deprecated', precompute='auto', max_iter=1000, tol=0.0001, cv=None, copy_X=True, verbose=0, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Elastic Net model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  Read more in the :ref:`User Guide <elastic_net>`.
 |  
 |  Parameters
 |  ----------
 |  l1_ratio : float or list of float, default=0.5
 |      Float between 0 and 1 passed to ElasticNet (scaling between
 |      l1 and l2 penalties). For ``l1_ratio = 0``
 |      the penalty is an L2 penalty. For ``l1_ratio = 1`` it is an L1 penalty.
 |      For ``0 < l1_ratio < 1``, the penalty is a combination of L1 and L2
 |      This parameter can 

In [61]:
elasticnetcv_model = ElasticNetCV(l1_ratio=[.1, .5 ,.7, .9, .95,.99 ,1.0], tol =0.01)

In [62]:
elasticnetcv_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0], tol=0.01)

In [63]:
elasticnetcv_model.l1_ratio_

1.0

In [64]:
test_prediction = elasticnetcv_model.predict(X_test)

In [65]:
MAE = mean_absolute_error(y_test, test_prediction)
MSE = mean_squared_error(y_test, test_prediction)
RMSE = np.sqrt(MSE)

In [66]:
MAE

0.5663262117569451

In [67]:
MSE

0.5603340214638839

In [68]:
RMSE

0.7485546215633726

In [69]:
elasticnetcv_model.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])